# whether to calculate diagnostics from scratch, if already saved
from_scratch: true

# number of threads for P(k) computation
threads: 16

# number of lhid to include for the visualization
n_seeds: 1
lhid_start: 0