- _idx: 0
  batch_size: 85
  fcn_depth: 3
  fcn_width: 25
  hidden_features: 25
  learning_rate: 0.0002693883019285411
  model: gf
  num_transforms: 5
- _idx: 1
  batch_size: 25
  fcn_depth: 0
  fcn_width: 56
  hidden_features: 25
  learning_rate: 2.616697456085447e-05
  model: gf
  num_transforms: 6
- _idx: 2
  batch_size: 40
  fcn_depth: 1
  fcn_width: 64
  hidden_features: 13
  learning_rate: 0.00017661199741399734
  model: gf
  num_transforms: 7
- _idx: 3
  batch_size: 36
  fcn_depth: 1
  fcn_width: 61
  hidden_features: 13
  learning_rate: 0.0002505870079649549
  model: gf
  num_transforms: 7
- _idx: 4
  batch_size: 65
  fcn_depth: 3
  fcn_width: 62
  hidden_features: 25
  learning_rate: 1.1888272947191953e-05
  model: gf
  num_transforms: 3
- _idx: 5
  batch_size: 49
  fcn_depth: 1
  fcn_width: 57
  hidden_features: 31
  learning_rate: 0.00013746795663394844
  model: gf
  num_transforms: 3
- _idx: 6
  batch_size: 62
  fcn_depth: 1
  fcn_width: 55
  hidden_features: 22
  learning_rate: 0.00030137109085330344
  model: gf
  num_transforms: 5
- _idx: 7
  batch_size: 222
  fcn_depth: 0
  fcn_width: 52
  hidden_features: 26
  learning_rate: 2.9067203620664195e-05
  model: gf
  num_transforms: 2
- _idx: 8
  batch_size: 63
  fcn_depth: 1
  fcn_width: 53
  hidden_features: 27
  learning_rate: 0.0002612740636763687
  model: gf
  num_transforms: 6
- _idx: 9
  batch_size: 22
  fcn_depth: 0
  fcn_width: 52
  hidden_features: 31
  learning_rate: 6.342561443203472e-05
  model: gf
  num_transforms: 3
- _idx: 10
  batch_size: 229
  fcn_depth: 2
  fcn_width: 43
  hidden_features: 26
  learning_rate: 0.0008827525444437128
  model: gf
  num_transforms: 2
- _idx: 11
  batch_size: 16
  fcn_depth: 3
  fcn_width: 28
  hidden_features: 28
  learning_rate: 0.00028261078307073313
  model: gf
  num_transforms: 5
- _idx: 12
  batch_size: 103
  fcn_depth: 0
  fcn_width: 51
  hidden_features: 11
  learning_rate: 1.5107968424215246e-05
  model: gf
  num_transforms: 4
- _idx: 13
  batch_size: 138
  fcn_depth: 2
  fcn_width: 41
  hidden_features: 18
  learning_rate: 1.8489723606626006e-05
  model: gf
  num_transforms: 5
- _idx: 14
  batch_size: 72
  fcn_depth: 0
  fcn_width: 29
  hidden_features: 16
  learning_rate: 0.0001993718997083525
  model: gf
  num_transforms: 3
- _idx: 15
  batch_size: 30
  fcn_depth: 2
  fcn_width: 48
  hidden_features: 11
  learning_rate: 0.0007978205565731538
  model: gf
  num_transforms: 8
- _idx: 16
  batch_size: 123
  fcn_depth: 3
  fcn_width: 23
  hidden_features: 15
  learning_rate: 5.0552323535452755e-05
  model: gf
  num_transforms: 4
- _idx: 17
  batch_size: 114
  fcn_depth: 0
  fcn_width: 64
  hidden_features: 26
  learning_rate: 0.0002605163143373722
  model: gf
  num_transforms: 9
- _idx: 18
  batch_size: 114
  fcn_depth: 3
  fcn_width: 44
  hidden_features: 18
  learning_rate: 0.0005971554644990547
  model: gf
  num_transforms: 4
- _idx: 19
  batch_size: 89
  fcn_depth: 2
  fcn_width: 49
  hidden_features: 21
  learning_rate: 0.00022963017790714307
  model: gf
  num_transforms: 3
- _idx: 20
  batch_size: 73
  fcn_depth: 2
  fcn_width: 17
  hidden_features: 25
  learning_rate: 0.00018969451303410678
  model: gf
  num_transforms: 7
- _idx: 21
  batch_size: 34
  fcn_depth: 0
  fcn_width: 63
  hidden_features: 31
  learning_rate: 0.00017557477384440886
  model: gf
  num_transforms: 8
- _idx: 22
  batch_size: 71
  fcn_depth: 0
  fcn_width: 60
  hidden_features: 31
  learning_rate: 3.797971940547788e-05
  model: gf
  num_transforms: 8
- _idx: 23
  batch_size: 46
  fcn_depth: 1
  fcn_width: 52
  hidden_features: 10
  learning_rate: 0.0009600266784735378
  model: gf
  num_transforms: 5
- _idx: 24
  batch_size: 64
  fcn_depth: 0
  fcn_width: 19
  hidden_features: 26
  learning_rate: 0.0005540787181959423
  model: gf
  num_transforms: 4
- _idx: 25
  batch_size: 58
  fcn_depth: 0
  fcn_width: 33
  hidden_features: 31
  learning_rate: 5.301247954312141e-05
  model: gf
  num_transforms: 2
- _idx: 26
  batch_size: 105
  fcn_depth: 2
  fcn_width: 56
  hidden_features: 14
  learning_rate: 4.528725544438216e-05
  model: gf
  num_transforms: 2
- _idx: 27
  batch_size: 76
  fcn_depth: 3
  fcn_width: 42
  hidden_features: 11
  learning_rate: 3.415023961086393e-05
  model: gf
  num_transforms: 7
- _idx: 28
  batch_size: 28
  fcn_depth: 2
  fcn_width: 21
  hidden_features: 28
  learning_rate: 0.0003646382854558486
  model: gf
  num_transforms: 2
- _idx: 29
  batch_size: 63
  fcn_depth: 2
  fcn_width: 51
  hidden_features: 11
  learning_rate: 1.5650059375475695e-05
  model: gf
  num_transforms: 7
- _idx: 30
  batch_size: 48
  fcn_depth: 3
  fcn_width: 50
  hidden_features: 31
  learning_rate: 0.00018983391239457822
  model: gf
  num_transforms: 4
- _idx: 31
  batch_size: 40
  fcn_depth: 3
  fcn_width: 44
  hidden_features: 10
  learning_rate: 0.0006230948280315917
  model: gf
  num_transforms: 4
- _idx: 32
  batch_size: 30
  fcn_depth: 3
  fcn_width: 28
  hidden_features: 32
  learning_rate: 6.181411554311239e-05
  model: gf
  num_transforms: 5
- _idx: 33
  batch_size: 44
  fcn_depth: 0
  fcn_width: 29
  hidden_features: 17
  learning_rate: 0.0005685878542104551
  model: gf
  num_transforms: 2
- _idx: 34
  batch_size: 194
  fcn_depth: 1
  fcn_width: 47
  hidden_features: 25
  learning_rate: 0.0003542965718667561
  model: gf
  num_transforms: 8
- _idx: 35
  batch_size: 23
  fcn_depth: 2
  fcn_width: 37
  hidden_features: 32
  learning_rate: 0.0004880562999295747
  model: gf
  num_transforms: 8
- _idx: 36
  batch_size: 180
  fcn_depth: 1
  fcn_width: 53
  hidden_features: 14
  learning_rate: 3.7769385178112066e-05
  model: gf
  num_transforms: 8
- _idx: 37
  batch_size: 19
  fcn_depth: 3
  fcn_width: 32
  hidden_features: 12
  learning_rate: 7.092567059706802e-05
  model: gf
  num_transforms: 6
- _idx: 38
  batch_size: 60
  fcn_depth: 0
  fcn_width: 62
  hidden_features: 23
  learning_rate: 0.0004206076074100964
  model: gf
  num_transforms: 4
- _idx: 39
  batch_size: 56
  fcn_depth: 2
  fcn_width: 53
  hidden_features: 15
  learning_rate: 1.160236640391389e-05
  model: gf
  num_transforms: 2
- _idx: 40
  batch_size: 240
  fcn_depth: 2
  fcn_width: 28
  hidden_features: 22
  learning_rate: 3.949379265619181e-05
  model: gf
  num_transforms: 3
- _idx: 41
  batch_size: 158
  fcn_depth: 0
  fcn_width: 62
  hidden_features: 14
  learning_rate: 0.0001286145543510402
  model: gf
  num_transforms: 2
- _idx: 42
  batch_size: 54
  fcn_depth: 1
  fcn_width: 52
  hidden_features: 28
  learning_rate: 0.0002522644933133886
  model: gf
  num_transforms: 4
- _idx: 43
  batch_size: 192
  fcn_depth: 2
  fcn_width: 44
  hidden_features: 24
  learning_rate: 0.00014994578090255398
  model: gf
  num_transforms: 7
- _idx: 44
  batch_size: 19
  fcn_depth: 1
  fcn_width: 39
  hidden_features: 19
  learning_rate: 3.201841791717253e-05
  model: gf
  num_transforms: 8
- _idx: 45
  batch_size: 210
  fcn_depth: 1
  fcn_width: 47
  hidden_features: 16
  learning_rate: 2.5192736333182977e-05
  model: gf
  num_transforms: 4
- _idx: 46
  batch_size: 245
  fcn_depth: 2
  fcn_width: 50
  hidden_features: 20
  learning_rate: 0.0004532034700083015
  model: gf
  num_transforms: 9
- _idx: 47
  batch_size: 110
  fcn_depth: 0
  fcn_width: 57
  hidden_features: 29
  learning_rate: 0.0003333292205511444
  model: gf
  num_transforms: 8
- _idx: 48
  batch_size: 113
  fcn_depth: 0
  fcn_width: 38
  hidden_features: 18
  learning_rate: 5.009511304879616e-05
  model: gf
  num_transforms: 9
- _idx: 49
  batch_size: 40
  fcn_depth: 3
  fcn_width: 31
  hidden_features: 12
  learning_rate: 0.0001947460599283743
  model: gf
  num_transforms: 9
- _idx: 50
  batch_size: 46
  fcn_depth: 0
  fcn_width: 27
  hidden_features: 13
  learning_rate: 1.178049677227882e-05
  model: gf
  num_transforms: 9
- _idx: 51
  batch_size: 232
  fcn_depth: 1
  fcn_width: 40
  hidden_features: 12
  learning_rate: 2.1808479184612547e-05
  model: gf
  num_transforms: 6
- _idx: 52
  batch_size: 236
  fcn_depth: 2
  fcn_width: 47
  hidden_features: 29
  learning_rate: 0.0001057210412466521
  model: gf
  num_transforms: 6
- _idx: 53
  batch_size: 38
  fcn_depth: 2
  fcn_width: 37
  hidden_features: 23
  learning_rate: 3.112820707334453e-05
  model: gf
  num_transforms: 6
- _idx: 54
  batch_size: 18
  fcn_depth: 3
  fcn_width: 51
  hidden_features: 21
  learning_rate: 0.00026530223080835314
  model: gf
  num_transforms: 3
- _idx: 55
  batch_size: 71
  fcn_depth: 1
  fcn_width: 26
  hidden_features: 16
  learning_rate: 0.00012123968451019413
  model: gf
  num_transforms: 2
- _idx: 56
  batch_size: 28
  fcn_depth: 0
  fcn_width: 33
  hidden_features: 22
  learning_rate: 1.318730129024302e-05
  model: gf
  num_transforms: 8
- _idx: 57
  batch_size: 23
  fcn_depth: 2
  fcn_width: 21
  hidden_features: 18
  learning_rate: 9.536078659225952e-05
  model: gf
  num_transforms: 4
- _idx: 58
  batch_size: 198
  fcn_depth: 2
  fcn_width: 16
  hidden_features: 13
  learning_rate: 0.0003476066875924078
  model: gf
  num_transforms: 6
- _idx: 59
  batch_size: 135
  fcn_depth: 0
  fcn_width: 43
  hidden_features: 21
  learning_rate: 9.453628718490497e-05
  model: gf
  num_transforms: 3
- _idx: 60
  batch_size: 19
  fcn_depth: 0
  fcn_width: 42
  hidden_features: 15
  learning_rate: 4.788522057335226e-05
  model: gf
  num_transforms: 5
- _idx: 61
  batch_size: 140
  fcn_depth: 3
  fcn_width: 27
  hidden_features: 17
  learning_rate: 0.00031812364916272397
  model: gf
  num_transforms: 8
- _idx: 62
  batch_size: 86
  fcn_depth: 0
  fcn_width: 41
  hidden_features: 19
  learning_rate: 4.006094177066085e-05
  model: gf
  num_transforms: 6
- _idx: 63
  batch_size: 202
  fcn_depth: 3
  fcn_width: 22
  hidden_features: 11
  learning_rate: 0.00026756882901191243
  model: gf
  num_transforms: 2
- _idx: 64
  batch_size: 18
  fcn_depth: 2
  fcn_width: 58
  hidden_features: 31
  learning_rate: 0.0001521744918940435
  model: gf
  num_transforms: 9
- _idx: 65
  batch_size: 18
  fcn_depth: 3
  fcn_width: 45
  hidden_features: 12
  learning_rate: 0.000721327209210792
  model: gf
  num_transforms: 2
- _idx: 66
  batch_size: 34
  fcn_depth: 3
  fcn_width: 57
  hidden_features: 20
  learning_rate: 1.0016931121908779e-05
  model: gf
  num_transforms: 7
- _idx: 67
  batch_size: 20
  fcn_depth: 2
  fcn_width: 53
  hidden_features: 22
  learning_rate: 0.0008074701035662168
  model: gf
  num_transforms: 8
- _idx: 68
  batch_size: 57
  fcn_depth: 1
  fcn_width: 27
  hidden_features: 28
  learning_rate: 0.0007785242312628914
  model: gf
  num_transforms: 3
- _idx: 69
  batch_size: 105
  fcn_depth: 1
  fcn_width: 39
  hidden_features: 15
  learning_rate: 0.0004277814489460365
  model: gf
  num_transforms: 4
- _idx: 70
  batch_size: 62
  fcn_depth: 2
  fcn_width: 42
  hidden_features: 31
  learning_rate: 0.00037575365804068996
  model: gf
  num_transforms: 2
- _idx: 71
  batch_size: 19
  fcn_depth: 3
  fcn_width: 22
  hidden_features: 16
  learning_rate: 0.00043335551148659176
  model: gf
  num_transforms: 8
- _idx: 72
  batch_size: 183
  fcn_depth: 1
  fcn_width: 32
  hidden_features: 19
  learning_rate: 0.00014327195183402248
  model: gf
  num_transforms: 5
- _idx: 73
  batch_size: 136
  fcn_depth: 1
  fcn_width: 27
  hidden_features: 20
  learning_rate: 1.5364130513212377e-05
  model: gf
  num_transforms: 6
- _idx: 74
  batch_size: 203
  fcn_depth: 0
  fcn_width: 47
  hidden_features: 27
  learning_rate: 1.8462749746055357e-05
  model: gf
  num_transforms: 9
- _idx: 75
  batch_size: 42
  fcn_depth: 1
  fcn_width: 37
  hidden_features: 21
  learning_rate: 3.7183464873736205e-05
  model: gf
  num_transforms: 9
- _idx: 76
  batch_size: 23
  fcn_depth: 1
  fcn_width: 17
  hidden_features: 22
  learning_rate: 2.949111995623775e-05
  model: gf
  num_transforms: 9
- _idx: 77
  batch_size: 110
  fcn_depth: 1
  fcn_width: 30
  hidden_features: 14
  learning_rate: 0.00027800273072713257
  model: gf
  num_transforms: 4
- _idx: 78
  batch_size: 17
  fcn_depth: 2
  fcn_width: 64
  hidden_features: 10
  learning_rate: 0.0005628584879544888
  model: gf
  num_transforms: 9
- _idx: 79
  batch_size: 68
  fcn_depth: 2
  fcn_width: 60
  hidden_features: 21
  learning_rate: 8.957111324685047e-05
  model: gf
  num_transforms: 3
- _idx: 80
  batch_size: 165
  fcn_depth: 2
  fcn_width: 39
  hidden_features: 26
  learning_rate: 2.7534674544928243e-05
  model: gf
  num_transforms: 9
- _idx: 81
  batch_size: 17
  fcn_depth: 3
  fcn_width: 27
  hidden_features: 27
  learning_rate: 0.0006428381445058555
  model: gf
  num_transforms: 4
- _idx: 82
  batch_size: 63
  fcn_depth: 3
  fcn_width: 50
  hidden_features: 20
  learning_rate: 0.0004804635931340405
  model: gf
  num_transforms: 5
- _idx: 83
  batch_size: 17
  fcn_depth: 0
  fcn_width: 35
  hidden_features: 14
  learning_rate: 0.00040391330631522887
  model: gf
  num_transforms: 7
- _idx: 84
  batch_size: 61
  fcn_depth: 0
  fcn_width: 59
  hidden_features: 14
  learning_rate: 0.0004358927153610627
  model: gf
  num_transforms: 4
- _idx: 85
  batch_size: 31
  fcn_depth: 2
  fcn_width: 22
  hidden_features: 18
  learning_rate: 5.16042498746653e-05
  model: gf
  num_transforms: 5
- _idx: 86
  batch_size: 52
  fcn_depth: 2
  fcn_width: 34
  hidden_features: 12
  learning_rate: 2.8893531637157155e-05
  model: gf
  num_transforms: 4
- _idx: 87
  batch_size: 26
  fcn_depth: 1
  fcn_width: 19
  hidden_features: 10
  learning_rate: 2.9811186677858636e-05
  model: gf
  num_transforms: 3
- _idx: 88
  batch_size: 39
  fcn_depth: 1
  fcn_width: 26
  hidden_features: 11
  learning_rate: 0.00022292284550411802
  model: gf
  num_transforms: 7
- _idx: 89
  batch_size: 59
  fcn_depth: 1
  fcn_width: 44
  hidden_features: 24
  learning_rate: 0.00037938190340024456
  model: gf
  num_transforms: 9
- _idx: 90
  batch_size: 87
  fcn_depth: 2
  fcn_width: 58
  hidden_features: 19
  learning_rate: 0.00014166682010818694
  model: gf
  num_transforms: 5
- _idx: 91
  batch_size: 143
  fcn_depth: 0
  fcn_width: 19
  hidden_features: 27
  learning_rate: 3.419414881025922e-05
  model: gf
  num_transforms: 7
- _idx: 92
  batch_size: 26
  fcn_depth: 1
  fcn_width: 63
  hidden_features: 24
  learning_rate: 0.0006807235844450792
  model: gf
  num_transforms: 5
- _idx: 93
  batch_size: 26
  fcn_depth: 1
  fcn_width: 22
  hidden_features: 18
  learning_rate: 0.00027046771041713954
  model: gf
  num_transforms: 9
- _idx: 94
  batch_size: 70
  fcn_depth: 0
  fcn_width: 50
  hidden_features: 26
  learning_rate: 0.0006610933282214174
  model: gf
  num_transforms: 6
- _idx: 95
  batch_size: 149
  fcn_depth: 1
  fcn_width: 45
  hidden_features: 30
  learning_rate: 0.000231554464112484
  model: gf
  num_transforms: 6
- _idx: 96
  batch_size: 76
  fcn_depth: 0
  fcn_width: 33
  hidden_features: 31
  learning_rate: 0.00046342232538832865
  model: gf
  num_transforms: 6
- _idx: 97
  batch_size: 97
  fcn_depth: 2
  fcn_width: 63
  hidden_features: 21
  learning_rate: 1.2344019771407768e-05
  model: gf
  num_transforms: 4
- _idx: 98
  batch_size: 35
  fcn_depth: 3
  fcn_width: 48
  hidden_features: 16
  learning_rate: 7.064898261023189e-05
  model: gf
  num_transforms: 9
- _idx: 99
  batch_size: 34
  fcn_depth: 2
  fcn_width: 23
  hidden_features: 21
  learning_rate: 0.00035699929898508456
  model: gf
  num_transforms: 2
