- _idx: 0
  batch_size: 96
  fcn_depth: 3
  fcn_width: 21
  hidden_features: 23
  learning_rate: 4.729250526161365e-05
  model: maf
  num_transforms: 2
- _idx: 1
  batch_size: 25
  fcn_depth: 3
  fcn_width: 16
  hidden_features: 13
  learning_rate: 0.00020243242216078065
  model: maf
  num_transforms: 4
- _idx: 2
  batch_size: 44
  fcn_depth: 2
  fcn_width: 16
  hidden_features: 15
  learning_rate: 2.47266182197764e-05
  model: maf
  num_transforms: 7
- _idx: 3
  batch_size: 236
  fcn_depth: 2
  fcn_width: 58
  hidden_features: 28
  learning_rate: 0.00022249449070487363
  model: maf
  num_transforms: 5
- _idx: 4
  batch_size: 85
  fcn_depth: 2
  fcn_width: 37
  hidden_features: 18
  learning_rate: 7.042228249480471e-05
  model: maf
  num_transforms: 3
- _idx: 5
  batch_size: 97
  fcn_depth: 0
  fcn_width: 19
  hidden_features: 11
  learning_rate: 0.0001408155117107858
  model: maf
  num_transforms: 7
- _idx: 6
  batch_size: 32
  fcn_depth: 2
  fcn_width: 20
  hidden_features: 10
  learning_rate: 0.0002895420290635752
  model: maf
  num_transforms: 6
- _idx: 7
  batch_size: 164
  fcn_depth: 3
  fcn_width: 46
  hidden_features: 29
  learning_rate: 8.439182912692421e-05
  model: maf
  num_transforms: 4
- _idx: 8
  batch_size: 142
  fcn_depth: 1
  fcn_width: 18
  hidden_features: 18
  learning_rate: 0.00014484192041986106
  model: maf
  num_transforms: 6
- _idx: 9
  batch_size: 139
  fcn_depth: 2
  fcn_width: 23
  hidden_features: 11
  learning_rate: 0.0005304195890213032
  model: maf
  num_transforms: 8
- _idx: 10
  batch_size: 44
  fcn_depth: 0
  fcn_width: 33
  hidden_features: 27
  learning_rate: 0.0001900837682018885
  model: maf
  num_transforms: 2
- _idx: 11
  batch_size: 105
  fcn_depth: 2
  fcn_width: 36
  hidden_features: 14
  learning_rate: 0.00011812858162629986
  model: maf
  num_transforms: 5
- _idx: 12
  batch_size: 26
  fcn_depth: 1
  fcn_width: 29
  hidden_features: 25
  learning_rate: 0.0008181095184874516
  model: maf
  num_transforms: 6
- _idx: 13
  batch_size: 89
  fcn_depth: 1
  fcn_width: 57
  hidden_features: 16
  learning_rate: 1.5665251706864227e-05
  model: maf
  num_transforms: 6
- _idx: 14
  batch_size: 84
  fcn_depth: 2
  fcn_width: 21
  hidden_features: 31
  learning_rate: 0.00019696692632692974
  model: maf
  num_transforms: 4
- _idx: 15
  batch_size: 36
  fcn_depth: 2
  fcn_width: 30
  hidden_features: 31
  learning_rate: 0.0008022050555198377
  model: maf
  num_transforms: 9
- _idx: 16
  batch_size: 80
  fcn_depth: 3
  fcn_width: 62
  hidden_features: 14
  learning_rate: 2.9928644475767836e-05
  model: maf
  num_transforms: 9
- _idx: 17
  batch_size: 42
  fcn_depth: 3
  fcn_width: 45
  hidden_features: 24
  learning_rate: 0.000996680560697299
  model: maf
  num_transforms: 5
- _idx: 18
  batch_size: 19
  fcn_depth: 1
  fcn_width: 32
  hidden_features: 16
  learning_rate: 1.9741091270127692e-05
  model: maf
  num_transforms: 3
- _idx: 19
  batch_size: 201
  fcn_depth: 1
  fcn_width: 47
  hidden_features: 24
  learning_rate: 0.00017812152326200252
  model: maf
  num_transforms: 3
- _idx: 20
  batch_size: 34
  fcn_depth: 3
  fcn_width: 42
  hidden_features: 23
  learning_rate: 0.0003561282598722622
  model: maf
  num_transforms: 4
- _idx: 21
  batch_size: 23
  fcn_depth: 3
  fcn_width: 48
  hidden_features: 22
  learning_rate: 0.00012651974182163685
  model: maf
  num_transforms: 4
- _idx: 22
  batch_size: 61
  fcn_depth: 0
  fcn_width: 22
  hidden_features: 26
  learning_rate: 0.0002772427642200224
  model: maf
  num_transforms: 8
- _idx: 23
  batch_size: 84
  fcn_depth: 0
  fcn_width: 50
  hidden_features: 13
  learning_rate: 8.149990857142564e-05
  model: maf
  num_transforms: 9
- _idx: 24
  batch_size: 123
  fcn_depth: 2
  fcn_width: 52
  hidden_features: 22
  learning_rate: 0.0005999566982205351
  model: maf
  num_transforms: 5
- _idx: 25
  batch_size: 31
  fcn_depth: 2
  fcn_width: 44
  hidden_features: 10
  learning_rate: 5.6492206996581206e-05
  model: maf
  num_transforms: 2
- _idx: 26
  batch_size: 89
  fcn_depth: 2
  fcn_width: 18
  hidden_features: 25
  learning_rate: 0.0001366759190672597
  model: maf
  num_transforms: 4
- _idx: 27
  batch_size: 50
  fcn_depth: 3
  fcn_width: 61
  hidden_features: 13
  learning_rate: 6.351201603902735e-05
  model: maf
  num_transforms: 6
- _idx: 28
  batch_size: 23
  fcn_depth: 1
  fcn_width: 20
  hidden_features: 17
  learning_rate: 0.00042438525269357987
  model: maf
  num_transforms: 6
- _idx: 29
  batch_size: 29
  fcn_depth: 0
  fcn_width: 29
  hidden_features: 13
  learning_rate: 0.0004269714050674344
  model: maf
  num_transforms: 3
- _idx: 30
  batch_size: 82
  fcn_depth: 2
  fcn_width: 21
  hidden_features: 26
  learning_rate: 0.00026544903652119743
  model: maf
  num_transforms: 2
- _idx: 31
  batch_size: 123
  fcn_depth: 3
  fcn_width: 33
  hidden_features: 15
  learning_rate: 0.00010321098361907505
  model: maf
  num_transforms: 2
- _idx: 32
  batch_size: 90
  fcn_depth: 1
  fcn_width: 38
  hidden_features: 25
  learning_rate: 4.299929480150827e-05
  model: maf
  num_transforms: 7
- _idx: 33
  batch_size: 16
  fcn_depth: 3
  fcn_width: 46
  hidden_features: 28
  learning_rate: 6.875016220313985e-05
  model: maf
  num_transforms: 4
- _idx: 34
  batch_size: 32
  fcn_depth: 2
  fcn_width: 62
  hidden_features: 10
  learning_rate: 0.0007074237444584162
  model: maf
  num_transforms: 4
- _idx: 35
  batch_size: 57
  fcn_depth: 3
  fcn_width: 44
  hidden_features: 26
  learning_rate: 0.00014024515787842157
  model: maf
  num_transforms: 8
- _idx: 36
  batch_size: 94
  fcn_depth: 3
  fcn_width: 52
  hidden_features: 31
  learning_rate: 5.632495632700609e-05
  model: maf
  num_transforms: 8
- _idx: 37
  batch_size: 91
  fcn_depth: 3
  fcn_width: 52
  hidden_features: 19
  learning_rate: 1.663583438231922e-05
  model: maf
  num_transforms: 9
- _idx: 38
  batch_size: 21
  fcn_depth: 2
  fcn_width: 43
  hidden_features: 20
  learning_rate: 0.0003832858993587687
  model: maf
  num_transforms: 5
- _idx: 39
  batch_size: 26
  fcn_depth: 1
  fcn_width: 40
  hidden_features: 17
  learning_rate: 4.506147995167949e-05
  model: maf
  num_transforms: 7
- _idx: 40
  batch_size: 16
  fcn_depth: 1
  fcn_width: 27
  hidden_features: 32
  learning_rate: 0.0005952866240506396
  model: maf
  num_transforms: 7
- _idx: 41
  batch_size: 44
  fcn_depth: 0
  fcn_width: 30
  hidden_features: 18
  learning_rate: 2.5002410415005307e-05
  model: maf
  num_transforms: 5
- _idx: 42
  batch_size: 250
  fcn_depth: 2
  fcn_width: 28
  hidden_features: 20
  learning_rate: 0.0009215004562398498
  model: maf
  num_transforms: 4
- _idx: 43
  batch_size: 55
  fcn_depth: 3
  fcn_width: 62
  hidden_features: 17
  learning_rate: 3.3202937578550155e-05
  model: maf
  num_transforms: 9
- _idx: 44
  batch_size: 127
  fcn_depth: 1
  fcn_width: 21
  hidden_features: 29
  learning_rate: 0.0009507454773347309
  model: maf
  num_transforms: 3
- _idx: 45
  batch_size: 109
  fcn_depth: 2
  fcn_width: 59
  hidden_features: 23
  learning_rate: 0.00036573241637924723
  model: maf
  num_transforms: 6
- _idx: 46
  batch_size: 253
  fcn_depth: 1
  fcn_width: 63
  hidden_features: 10
  learning_rate: 0.00010000985662809411
  model: maf
  num_transforms: 7
- _idx: 47
  batch_size: 107
  fcn_depth: 2
  fcn_width: 58
  hidden_features: 13
  learning_rate: 3.0296465453850995e-05
  model: maf
  num_transforms: 4
- _idx: 48
  batch_size: 17
  fcn_depth: 2
  fcn_width: 39
  hidden_features: 22
  learning_rate: 0.0001696444954012678
  model: maf
  num_transforms: 3
- _idx: 49
  batch_size: 17
  fcn_depth: 1
  fcn_width: 53
  hidden_features: 20
  learning_rate: 0.0007727961198545299
  model: maf
  num_transforms: 5
- _idx: 50
  batch_size: 29
  fcn_depth: 2
  fcn_width: 50
  hidden_features: 22
  learning_rate: 0.00010770786106932135
  model: maf
  num_transforms: 6
- _idx: 51
  batch_size: 37
  fcn_depth: 0
  fcn_width: 45
  hidden_features: 19
  learning_rate: 0.0008468880064586234
  model: maf
  num_transforms: 5
- _idx: 52
  batch_size: 24
  fcn_depth: 2
  fcn_width: 27
  hidden_features: 22
  learning_rate: 0.00013793307742700428
  model: maf
  num_transforms: 9
- _idx: 53
  batch_size: 98
  fcn_depth: 2
  fcn_width: 22
  hidden_features: 28
  learning_rate: 9.700942369575599e-05
  model: maf
  num_transforms: 6
- _idx: 54
  batch_size: 198
  fcn_depth: 2
  fcn_width: 27
  hidden_features: 15
  learning_rate: 1.614269922997467e-05
  model: maf
  num_transforms: 3
- _idx: 55
  batch_size: 79
  fcn_depth: 2
  fcn_width: 31
  hidden_features: 18
  learning_rate: 0.000127829322391456
  model: maf
  num_transforms: 3
- _idx: 56
  batch_size: 86
  fcn_depth: 1
  fcn_width: 45
  hidden_features: 13
  learning_rate: 3.492224789528077e-05
  model: maf
  num_transforms: 8
- _idx: 57
  batch_size: 194
  fcn_depth: 3
  fcn_width: 64
  hidden_features: 17
  learning_rate: 5.2348748327609624e-05
  model: maf
  num_transforms: 6
- _idx: 58
  batch_size: 101
  fcn_depth: 1
  fcn_width: 18
  hidden_features: 18
  learning_rate: 0.0007231651333089201
  model: maf
  num_transforms: 2
- _idx: 59
  batch_size: 135
  fcn_depth: 0
  fcn_width: 52
  hidden_features: 11
  learning_rate: 0.00026992580969941533
  model: maf
  num_transforms: 2
- _idx: 60
  batch_size: 49
  fcn_depth: 2
  fcn_width: 29
  hidden_features: 30
  learning_rate: 0.00032075432552712183
  model: maf
  num_transforms: 7
- _idx: 61
  batch_size: 107
  fcn_depth: 2
  fcn_width: 19
  hidden_features: 19
  learning_rate: 0.00019104214559629255
  model: maf
  num_transforms: 4
- _idx: 62
  batch_size: 38
  fcn_depth: 3
  fcn_width: 26
  hidden_features: 21
  learning_rate: 0.00027847296401616874
  model: maf
  num_transforms: 4
- _idx: 63
  batch_size: 46
  fcn_depth: 0
  fcn_width: 22
  hidden_features: 14
  learning_rate: 6.8338632513764e-05
  model: maf
  num_transforms: 3
- _idx: 64
  batch_size: 138
  fcn_depth: 0
  fcn_width: 47
  hidden_features: 26
  learning_rate: 0.0004906016870931991
  model: maf
  num_transforms: 6
- _idx: 65
  batch_size: 178
  fcn_depth: 3
  fcn_width: 35
  hidden_features: 20
  learning_rate: 0.0003359544983083456
  model: maf
  num_transforms: 5
- _idx: 66
  batch_size: 139
  fcn_depth: 3
  fcn_width: 28
  hidden_features: 22
  learning_rate: 9.330051248907976e-05
  model: maf
  num_transforms: 4
- _idx: 67
  batch_size: 51
  fcn_depth: 1
  fcn_width: 37
  hidden_features: 23
  learning_rate: 5.8963481439663226e-05
  model: maf
  num_transforms: 7
- _idx: 68
  batch_size: 101
  fcn_depth: 2
  fcn_width: 53
  hidden_features: 20
  learning_rate: 7.422194290900738e-05
  model: maf
  num_transforms: 8
- _idx: 69
  batch_size: 133
  fcn_depth: 2
  fcn_width: 43
  hidden_features: 18
  learning_rate: 3.463078897258919e-05
  model: maf
  num_transforms: 2
- _idx: 70
  batch_size: 60
  fcn_depth: 0
  fcn_width: 24
  hidden_features: 14
  learning_rate: 5.281320165536637e-05
  model: maf
  num_transforms: 4
- _idx: 71
  batch_size: 111
  fcn_depth: 3
  fcn_width: 60
  hidden_features: 24
  learning_rate: 0.0008867202936965535
  model: maf
  num_transforms: 7
- _idx: 72
  batch_size: 98
  fcn_depth: 0
  fcn_width: 60
  hidden_features: 27
  learning_rate: 0.0003529112847628081
  model: maf
  num_transforms: 8
- _idx: 73
  batch_size: 44
  fcn_depth: 3
  fcn_width: 51
  hidden_features: 22
  learning_rate: 0.0006726949076893702
  model: maf
  num_transforms: 5
- _idx: 74
  batch_size: 180
  fcn_depth: 2
  fcn_width: 17
  hidden_features: 13
  learning_rate: 0.0001313701210434938
  model: maf
  num_transforms: 4
- _idx: 75
  batch_size: 161
  fcn_depth: 0
  fcn_width: 30
  hidden_features: 24
  learning_rate: 0.00034320624938204445
  model: maf
  num_transforms: 8
- _idx: 76
  batch_size: 22
  fcn_depth: 0
  fcn_width: 21
  hidden_features: 14
  learning_rate: 0.00074859348142902
  model: maf
  num_transforms: 6
- _idx: 77
  batch_size: 154
  fcn_depth: 2
  fcn_width: 32
  hidden_features: 11
  learning_rate: 0.00021473499256016075
  model: maf
  num_transforms: 8
- _idx: 78
  batch_size: 42
  fcn_depth: 2
  fcn_width: 19
  hidden_features: 18
  learning_rate: 3.091947379701676e-05
  model: maf
  num_transforms: 5
- _idx: 79
  batch_size: 143
  fcn_depth: 2
  fcn_width: 30
  hidden_features: 30
  learning_rate: 0.0004081711776909031
  model: maf
  num_transforms: 5
- _idx: 80
  batch_size: 45
  fcn_depth: 3
  fcn_width: 55
  hidden_features: 31
  learning_rate: 0.00043914400203126045
  model: maf
  num_transforms: 6
- _idx: 81
  batch_size: 51
  fcn_depth: 2
  fcn_width: 16
  hidden_features: 19
  learning_rate: 0.00019377066387197978
  model: maf
  num_transforms: 6
- _idx: 82
  batch_size: 42
  fcn_depth: 3
  fcn_width: 42
  hidden_features: 14
  learning_rate: 0.0008641139842392144
  model: maf
  num_transforms: 2
- _idx: 83
  batch_size: 22
  fcn_depth: 1
  fcn_width: 43
  hidden_features: 14
  learning_rate: 0.0001825967270565745
  model: maf
  num_transforms: 7
- _idx: 84
  batch_size: 21
  fcn_depth: 1
  fcn_width: 38
  hidden_features: 23
  learning_rate: 1.6889484569544934e-05
  model: maf
  num_transforms: 7
- _idx: 85
  batch_size: 192
  fcn_depth: 3
  fcn_width: 45
  hidden_features: 32
  learning_rate: 4.570058585810739e-05
  model: maf
  num_transforms: 2
- _idx: 86
  batch_size: 39
  fcn_depth: 0
  fcn_width: 55
  hidden_features: 30
  learning_rate: 1.4326816827898578e-05
  model: maf
  num_transforms: 3
- _idx: 87
  batch_size: 30
  fcn_depth: 0
  fcn_width: 57
  hidden_features: 16
  learning_rate: 0.00010024781548184703
  model: maf
  num_transforms: 4
- _idx: 88
  batch_size: 122
  fcn_depth: 2
  fcn_width: 45
  hidden_features: 20
  learning_rate: 0.0001389936286196284
  model: maf
  num_transforms: 8
- _idx: 89
  batch_size: 120
  fcn_depth: 1
  fcn_width: 49
  hidden_features: 29
  learning_rate: 1.0612931607406455e-05
  model: maf
  num_transforms: 6
- _idx: 90
  batch_size: 59
  fcn_depth: 2
  fcn_width: 42
  hidden_features: 10
  learning_rate: 3.0654560957120525e-05
  model: maf
  num_transforms: 8
- _idx: 91
  batch_size: 80
  fcn_depth: 0
  fcn_width: 54
  hidden_features: 15
  learning_rate: 0.00013156521150517624
  model: maf
  num_transforms: 9
- _idx: 92
  batch_size: 19
  fcn_depth: 3
  fcn_width: 48
  hidden_features: 12
  learning_rate: 3.2198329023964004e-05
  model: maf
  num_transforms: 3
- _idx: 93
  batch_size: 16
  fcn_depth: 1
  fcn_width: 17
  hidden_features: 19
  learning_rate: 1.9588839021357744e-05
  model: maf
  num_transforms: 8
- _idx: 94
  batch_size: 220
  fcn_depth: 0
  fcn_width: 44
  hidden_features: 28
  learning_rate: 2.896222005261305e-05
  model: maf
  num_transforms: 7
- _idx: 95
  batch_size: 38
  fcn_depth: 2
  fcn_width: 59
  hidden_features: 30
  learning_rate: 2.0349584928062466e-05
  model: maf
  num_transforms: 2
- _idx: 96
  batch_size: 30
  fcn_depth: 0
  fcn_width: 21
  hidden_features: 26
  learning_rate: 3.48635225230742e-05
  model: maf
  num_transforms: 9
- _idx: 97
  batch_size: 99
  fcn_depth: 3
  fcn_width: 64
  hidden_features: 27
  learning_rate: 7.351698902354487e-05
  model: maf
  num_transforms: 4
- _idx: 98
  batch_size: 25
  fcn_depth: 2
  fcn_width: 46
  hidden_features: 25
  learning_rate: 0.00010357881530975454
  model: maf
  num_transforms: 9
- _idx: 99
  batch_size: 81
  fcn_depth: 1
  fcn_width: 16
  hidden_features: 18
  learning_rate: 7.063144809062992e-05
  model: maf
  num_transforms: 3
