- _idx: 0
  batch_size: 69
  fcn_depth: 1
  fcn_width: 53
  hidden_features: 11
  learning_rate: 0.0003832216850492786
  model: nsf
  num_transforms: 2
- _idx: 1
  batch_size: 33
  fcn_depth: 2
  fcn_width: 57
  hidden_features: 24
  learning_rate: 0.00013589482177682
  model: nsf
  num_transforms: 5
- _idx: 2
  batch_size: 34
  fcn_depth: 3
  fcn_width: 18
  hidden_features: 11
  learning_rate: 1.4663072613477658e-05
  model: nsf
  num_transforms: 2
- _idx: 3
  batch_size: 31
  fcn_depth: 3
  fcn_width: 24
  hidden_features: 21
  learning_rate: 0.0008401891913442225
  model: nsf
  num_transforms: 5
- _idx: 4
  batch_size: 189
  fcn_depth: 2
  fcn_width: 48
  hidden_features: 12
  learning_rate: 0.00018960166746974746
  model: nsf
  num_transforms: 7
- _idx: 5
  batch_size: 20
  fcn_depth: 2
  fcn_width: 21
  hidden_features: 25
  learning_rate: 1.916583786386708e-05
  model: nsf
  num_transforms: 5
- _idx: 6
  batch_size: 26
  fcn_depth: 3
  fcn_width: 50
  hidden_features: 11
  learning_rate: 4.763983334579926e-05
  model: nsf
  num_transforms: 2
- _idx: 7
  batch_size: 74
  fcn_depth: 1
  fcn_width: 18
  hidden_features: 27
  learning_rate: 0.0008491404616855589
  model: nsf
  num_transforms: 6
- _idx: 8
  batch_size: 56
  fcn_depth: 0
  fcn_width: 52
  hidden_features: 27
  learning_rate: 0.00022895962906132288
  model: nsf
  num_transforms: 5
- _idx: 9
  batch_size: 17
  fcn_depth: 3
  fcn_width: 17
  hidden_features: 21
  learning_rate: 0.00027807460232289746
  model: nsf
  num_transforms: 7
- _idx: 10
  batch_size: 121
  fcn_depth: 0
  fcn_width: 51
  hidden_features: 31
  learning_rate: 0.0003151438483996214
  model: nsf
  num_transforms: 4
- _idx: 11
  batch_size: 21
  fcn_depth: 2
  fcn_width: 54
  hidden_features: 27
  learning_rate: 3.031499911070511e-05
  model: nsf
  num_transforms: 3
- _idx: 12
  batch_size: 67
  fcn_depth: 2
  fcn_width: 30
  hidden_features: 29
  learning_rate: 1.4253216895303305e-05
  model: nsf
  num_transforms: 5
- _idx: 13
  batch_size: 182
  fcn_depth: 2
  fcn_width: 28
  hidden_features: 13
  learning_rate: 0.0003988016295438443
  model: nsf
  num_transforms: 8
- _idx: 14
  batch_size: 130
  fcn_depth: 3
  fcn_width: 56
  hidden_features: 29
  learning_rate: 4.5231480496894884e-05
  model: nsf
  num_transforms: 6
- _idx: 15
  batch_size: 24
  fcn_depth: 0
  fcn_width: 47
  hidden_features: 28
  learning_rate: 0.0004276097878757326
  model: nsf
  num_transforms: 8
- _idx: 16
  batch_size: 120
  fcn_depth: 1
  fcn_width: 32
  hidden_features: 24
  learning_rate: 7.847956537267754e-05
  model: nsf
  num_transforms: 2
- _idx: 17
  batch_size: 43
  fcn_depth: 3
  fcn_width: 17
  hidden_features: 18
  learning_rate: 5.137332757520743e-05
  model: nsf
  num_transforms: 4
- _idx: 18
  batch_size: 31
  fcn_depth: 3
  fcn_width: 61
  hidden_features: 20
  learning_rate: 3.7739574093234044e-05
  model: nsf
  num_transforms: 2
- _idx: 19
  batch_size: 159
  fcn_depth: 2
  fcn_width: 40
  hidden_features: 15
  learning_rate: 5.261276436465826e-05
  model: nsf
  num_transforms: 9
- _idx: 20
  batch_size: 36
  fcn_depth: 2
  fcn_width: 64
  hidden_features: 11
  learning_rate: 0.0006455006606651479
  model: nsf
  num_transforms: 5
- _idx: 21
  batch_size: 92
  fcn_depth: 3
  fcn_width: 57
  hidden_features: 29
  learning_rate: 1.689014122070191e-05
  model: nsf
  num_transforms: 4
- _idx: 22
  batch_size: 42
  fcn_depth: 2
  fcn_width: 17
  hidden_features: 27
  learning_rate: 0.00010946761570599663
  model: nsf
  num_transforms: 6
- _idx: 23
  batch_size: 23
  fcn_depth: 1
  fcn_width: 52
  hidden_features: 16
  learning_rate: 6.838687356454338e-05
  model: nsf
  num_transforms: 3
- _idx: 24
  batch_size: 241
  fcn_depth: 1
  fcn_width: 55
  hidden_features: 14
  learning_rate: 1.0929523114890525e-05
  model: nsf
  num_transforms: 3
- _idx: 25
  batch_size: 114
  fcn_depth: 2
  fcn_width: 37
  hidden_features: 16
  learning_rate: 1.14939820882621e-05
  model: nsf
  num_transforms: 5
- _idx: 26
  batch_size: 20
  fcn_depth: 3
  fcn_width: 24
  hidden_features: 28
  learning_rate: 0.0006985908990544106
  model: nsf
  num_transforms: 3
- _idx: 27
  batch_size: 17
  fcn_depth: 3
  fcn_width: 39
  hidden_features: 32
  learning_rate: 3.1246221786888624e-05
  model: nsf
  num_transforms: 4
- _idx: 28
  batch_size: 103
  fcn_depth: 3
  fcn_width: 64
  hidden_features: 12
  learning_rate: 0.0006253522466352009
  model: nsf
  num_transforms: 7
- _idx: 29
  batch_size: 20
  fcn_depth: 3
  fcn_width: 58
  hidden_features: 19
  learning_rate: 1.8487528797394325e-05
  model: nsf
  num_transforms: 2
- _idx: 30
  batch_size: 51
  fcn_depth: 1
  fcn_width: 42
  hidden_features: 29
  learning_rate: 0.0009118526250323966
  model: nsf
  num_transforms: 6
- _idx: 31
  batch_size: 18
  fcn_depth: 1
  fcn_width: 41
  hidden_features: 31
  learning_rate: 2.9547836547603636e-05
  model: nsf
  num_transforms: 3
- _idx: 32
  batch_size: 112
  fcn_depth: 3
  fcn_width: 55
  hidden_features: 12
  learning_rate: 0.00016316096531713453
  model: nsf
  num_transforms: 8
- _idx: 33
  batch_size: 117
  fcn_depth: 2
  fcn_width: 27
  hidden_features: 14
  learning_rate: 0.0003478155476524867
  model: nsf
  num_transforms: 7
- _idx: 34
  batch_size: 21
  fcn_depth: 3
  fcn_width: 25
  hidden_features: 22
  learning_rate: 2.7719978722788432e-05
  model: nsf
  num_transforms: 8
- _idx: 35
  batch_size: 47
  fcn_depth: 1
  fcn_width: 55
  hidden_features: 31
  learning_rate: 0.000618561068318673
  model: nsf
  num_transforms: 5
- _idx: 36
  batch_size: 107
  fcn_depth: 3
  fcn_width: 32
  hidden_features: 30
  learning_rate: 2.1887657187666675e-05
  model: nsf
  num_transforms: 8
- _idx: 37
  batch_size: 95
  fcn_depth: 3
  fcn_width: 43
  hidden_features: 24
  learning_rate: 0.0001413920334098474
  model: nsf
  num_transforms: 6
- _idx: 38
  batch_size: 30
  fcn_depth: 1
  fcn_width: 32
  hidden_features: 14
  learning_rate: 0.00023493880858322354
  model: nsf
  num_transforms: 9
- _idx: 39
  batch_size: 239
  fcn_depth: 1
  fcn_width: 55
  hidden_features: 31
  learning_rate: 0.0002842863002749872
  model: nsf
  num_transforms: 5
- _idx: 40
  batch_size: 26
  fcn_depth: 3
  fcn_width: 33
  hidden_features: 29
  learning_rate: 0.00026357943275323234
  model: nsf
  num_transforms: 7
- _idx: 41
  batch_size: 180
  fcn_depth: 0
  fcn_width: 32
  hidden_features: 20
  learning_rate: 3.264624889575617e-05
  model: nsf
  num_transforms: 4
- _idx: 42
  batch_size: 23
  fcn_depth: 1
  fcn_width: 52
  hidden_features: 12
  learning_rate: 0.0002963383057825453
  model: nsf
  num_transforms: 9
- _idx: 43
  batch_size: 119
  fcn_depth: 1
  fcn_width: 51
  hidden_features: 18
  learning_rate: 0.0002082263722544956
  model: nsf
  num_transforms: 8
- _idx: 44
  batch_size: 219
  fcn_depth: 0
  fcn_width: 56
  hidden_features: 17
  learning_rate: 0.00014062537036449275
  model: nsf
  num_transforms: 9
- _idx: 45
  batch_size: 183
  fcn_depth: 3
  fcn_width: 17
  hidden_features: 17
  learning_rate: 1.3751982707855475e-05
  model: nsf
  num_transforms: 8
- _idx: 46
  batch_size: 82
  fcn_depth: 1
  fcn_width: 51
  hidden_features: 18
  learning_rate: 4.058327722911953e-05
  model: nsf
  num_transforms: 6
- _idx: 47
  batch_size: 18
  fcn_depth: 2
  fcn_width: 38
  hidden_features: 15
  learning_rate: 0.00026154160339903935
  model: nsf
  num_transforms: 4
- _idx: 48
  batch_size: 225
  fcn_depth: 0
  fcn_width: 17
  hidden_features: 21
  learning_rate: 2.8107823893021583e-05
  model: nsf
  num_transforms: 5
- _idx: 49
  batch_size: 125
  fcn_depth: 2
  fcn_width: 36
  hidden_features: 29
  learning_rate: 9.554776439176081e-05
  model: nsf
  num_transforms: 5
- _idx: 50
  batch_size: 62
  fcn_depth: 0
  fcn_width: 25
  hidden_features: 27
  learning_rate: 0.0004973825442948892
  model: nsf
  num_transforms: 3
- _idx: 51
  batch_size: 170
  fcn_depth: 1
  fcn_width: 41
  hidden_features: 17
  learning_rate: 0.0002014880017019968
  model: nsf
  num_transforms: 6
- _idx: 52
  batch_size: 61
  fcn_depth: 0
  fcn_width: 43
  hidden_features: 29
  learning_rate: 1.0641856864237427e-05
  model: nsf
  num_transforms: 3
- _idx: 53
  batch_size: 23
  fcn_depth: 0
  fcn_width: 18
  hidden_features: 21
  learning_rate: 0.0003539988977562726
  model: nsf
  num_transforms: 5
- _idx: 54
  batch_size: 36
  fcn_depth: 1
  fcn_width: 30
  hidden_features: 20
  learning_rate: 0.0007029283776547096
  model: nsf
  num_transforms: 5
- _idx: 55
  batch_size: 47
  fcn_depth: 0
  fcn_width: 59
  hidden_features: 17
  learning_rate: 0.0002481192739521394
  model: nsf
  num_transforms: 7
- _idx: 56
  batch_size: 103
  fcn_depth: 0
  fcn_width: 44
  hidden_features: 22
  learning_rate: 0.00019697890288179127
  model: nsf
  num_transforms: 9
- _idx: 57
  batch_size: 106
  fcn_depth: 1
  fcn_width: 17
  hidden_features: 25
  learning_rate: 8.352544268874728e-05
  model: nsf
  num_transforms: 4
- _idx: 58
  batch_size: 25
  fcn_depth: 0
  fcn_width: 28
  hidden_features: 12
  learning_rate: 0.00010113608747741026
  model: nsf
  num_transforms: 2
- _idx: 59
  batch_size: 32
  fcn_depth: 0
  fcn_width: 43
  hidden_features: 21
  learning_rate: 1.5696108677889513e-05
  model: nsf
  num_transforms: 4
- _idx: 60
  batch_size: 192
  fcn_depth: 1
  fcn_width: 64
  hidden_features: 14
  learning_rate: 3.418940979083587e-05
  model: nsf
  num_transforms: 6
- _idx: 61
  batch_size: 89
  fcn_depth: 2
  fcn_width: 21
  hidden_features: 13
  learning_rate: 0.000751153592891
  model: nsf
  num_transforms: 4
- _idx: 62
  batch_size: 66
  fcn_depth: 1
  fcn_width: 32
  hidden_features: 10
  learning_rate: 1.4560027914584131e-05
  model: nsf
  num_transforms: 9
- _idx: 63
  batch_size: 45
  fcn_depth: 1
  fcn_width: 56
  hidden_features: 10
  learning_rate: 0.0003246952703506012
  model: nsf
  num_transforms: 6
- _idx: 64
  batch_size: 73
  fcn_depth: 3
  fcn_width: 46
  hidden_features: 28
  learning_rate: 3.7523680182061865e-05
  model: nsf
  num_transforms: 8
- _idx: 65
  batch_size: 144
  fcn_depth: 3
  fcn_width: 41
  hidden_features: 31
  learning_rate: 3.597326770145701e-05
  model: nsf
  num_transforms: 8
- _idx: 66
  batch_size: 44
  fcn_depth: 0
  fcn_width: 32
  hidden_features: 10
  learning_rate: 4.238197817323015e-05
  model: nsf
  num_transforms: 9
- _idx: 67
  batch_size: 235
  fcn_depth: 0
  fcn_width: 61
  hidden_features: 14
  learning_rate: 0.00019482914154827732
  model: nsf
  num_transforms: 7
- _idx: 68
  batch_size: 54
  fcn_depth: 1
  fcn_width: 30
  hidden_features: 17
  learning_rate: 0.00019302197304862045
  model: nsf
  num_transforms: 5
- _idx: 69
  batch_size: 35
  fcn_depth: 3
  fcn_width: 22
  hidden_features: 24
  learning_rate: 2.4739999799686202e-05
  model: nsf
  num_transforms: 3
- _idx: 70
  batch_size: 86
  fcn_depth: 2
  fcn_width: 37
  hidden_features: 15
  learning_rate: 0.00011122891684715026
  model: nsf
  num_transforms: 7
- _idx: 71
  batch_size: 27
  fcn_depth: 0
  fcn_width: 29
  hidden_features: 19
  learning_rate: 5.4967258570767334e-05
  model: nsf
  num_transforms: 8
- _idx: 72
  batch_size: 135
  fcn_depth: 3
  fcn_width: 60
  hidden_features: 21
  learning_rate: 0.0001452235885541079
  model: nsf
  num_transforms: 3
- _idx: 73
  batch_size: 28
  fcn_depth: 1
  fcn_width: 42
  hidden_features: 28
  learning_rate: 3.408626408450582e-05
  model: nsf
  num_transforms: 3
- _idx: 74
  batch_size: 86
  fcn_depth: 0
  fcn_width: 61
  hidden_features: 19
  learning_rate: 0.0001056902353682351
  model: nsf
  num_transforms: 4
- _idx: 75
  batch_size: 39
  fcn_depth: 2
  fcn_width: 50
  hidden_features: 16
  learning_rate: 1.675497413528524e-05
  model: nsf
  num_transforms: 9
- _idx: 76
  batch_size: 41
  fcn_depth: 1
  fcn_width: 29
  hidden_features: 28
  learning_rate: 2.6254603127988497e-05
  model: nsf
  num_transforms: 4
- _idx: 77
  batch_size: 81
  fcn_depth: 1
  fcn_width: 63
  hidden_features: 22
  learning_rate: 0.00023583150082939205
  model: nsf
  num_transforms: 3
- _idx: 78
  batch_size: 157
  fcn_depth: 3
  fcn_width: 46
  hidden_features: 27
  learning_rate: 0.0002740045853049017
  model: nsf
  num_transforms: 2
- _idx: 79
  batch_size: 96
  fcn_depth: 0
  fcn_width: 19
  hidden_features: 25
  learning_rate: 0.0006174258337788856
  model: nsf
  num_transforms: 9
- _idx: 80
  batch_size: 26
  fcn_depth: 2
  fcn_width: 56
  hidden_features: 30
  learning_rate: 0.00016526762874258458
  model: nsf
  num_transforms: 2
- _idx: 81
  batch_size: 21
  fcn_depth: 0
  fcn_width: 50
  hidden_features: 21
  learning_rate: 0.0001168009145143821
  model: nsf
  num_transforms: 8
- _idx: 82
  batch_size: 168
  fcn_depth: 3
  fcn_width: 51
  hidden_features: 15
  learning_rate: 5.352653732585262e-05
  model: nsf
  num_transforms: 5
- _idx: 83
  batch_size: 27
  fcn_depth: 3
  fcn_width: 55
  hidden_features: 29
  learning_rate: 6.083589486544783e-05
  model: nsf
  num_transforms: 3
- _idx: 84
  batch_size: 77
  fcn_depth: 1
  fcn_width: 42
  hidden_features: 20
  learning_rate: 0.00010782669483999971
  model: nsf
  num_transforms: 3
- _idx: 85
  batch_size: 130
  fcn_depth: 0
  fcn_width: 55
  hidden_features: 26
  learning_rate: 3.204112494452179e-05
  model: nsf
  num_transforms: 8
- _idx: 86
  batch_size: 150
  fcn_depth: 2
  fcn_width: 48
  hidden_features: 29
  learning_rate: 0.00011626290145284018
  model: nsf
  num_transforms: 5
- _idx: 87
  batch_size: 19
  fcn_depth: 1
  fcn_width: 41
  hidden_features: 16
  learning_rate: 5.520094390154931e-05
  model: nsf
  num_transforms: 6
- _idx: 88
  batch_size: 58
  fcn_depth: 1
  fcn_width: 33
  hidden_features: 31
  learning_rate: 8.143280575954363e-05
  model: nsf
  num_transforms: 8
- _idx: 89
  batch_size: 205
  fcn_depth: 1
  fcn_width: 63
  hidden_features: 14
  learning_rate: 0.0001329582327147694
  model: nsf
  num_transforms: 8
- _idx: 90
  batch_size: 94
  fcn_depth: 0
  fcn_width: 24
  hidden_features: 31
  learning_rate: 8.483596927244319e-05
  model: nsf
  num_transforms: 9
- _idx: 91
  batch_size: 133
  fcn_depth: 3
  fcn_width: 27
  hidden_features: 16
  learning_rate: 0.0008475901199256349
  model: nsf
  num_transforms: 6
- _idx: 92
  batch_size: 60
  fcn_depth: 0
  fcn_width: 42
  hidden_features: 17
  learning_rate: 0.0007042982430901246
  model: nsf
  num_transforms: 9
- _idx: 93
  batch_size: 238
  fcn_depth: 0
  fcn_width: 56
  hidden_features: 23
  learning_rate: 0.0007067171398460108
  model: nsf
  num_transforms: 7
- _idx: 94
  batch_size: 67
  fcn_depth: 2
  fcn_width: 17
  hidden_features: 23
  learning_rate: 0.000286258237280011
  model: nsf
  num_transforms: 7
- _idx: 95
  batch_size: 95
  fcn_depth: 3
  fcn_width: 28
  hidden_features: 24
  learning_rate: 0.0001357960052558851
  model: nsf
  num_transforms: 5
- _idx: 96
  batch_size: 54
  fcn_depth: 1
  fcn_width: 18
  hidden_features: 25
  learning_rate: 0.0009064946453120144
  model: nsf
  num_transforms: 9
- _idx: 97
  batch_size: 118
  fcn_depth: 2
  fcn_width: 37
  hidden_features: 28
  learning_rate: 0.00042578005817634087
  model: nsf
  num_transforms: 5
- _idx: 98
  batch_size: 64
  fcn_depth: 2
  fcn_width: 24
  hidden_features: 17
  learning_rate: 8.312456016166992e-05
  model: nsf
  num_transforms: 2
- _idx: 99
  batch_size: 88
  fcn_depth: 2
  fcn_width: 35
  hidden_features: 10
  learning_rate: 2.0165287209230253e-05
  model: nsf
  num_transforms: 2
