
defaults:
  - global
  - _self_

nbody:
  L: 1000           # Mpc/h
  N: 128            # meshgrid resolution
  lhid: 3
  matchIC: 2

  supersampling: 2  # particles resolution relative to meshgrid
  B: 2              # force grid resolution relative to particle grid
  N_steps: 64

  zi: 127
  zf: 0.0

  save_particles: false
